export const BASE_URL = "http://localhost:8080"
export const CATEGORY = "/category"
export const COMPETITION_URL = "/competition"
export const UPDATE = "/update"
export const SEASON = "/seasons/"
export const PLAYERS = "/players"
export const LOL = "/lol"